name: coverage

on:
  push:
    branches:
      - "*"
      - "!gh-pages"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt install ccache libgtest-dev lcov

      - name: Generate coverage report
        run: cmake --workflow --preset make-gcc-debug-coverage

      - name: Deploy coverage report
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          target-folder: ${{ github.ref_name }}/coverage
          folder: build/make-gcc-debug-coverage/lcov
          clean: true
