name: documentation

on:
  push:
    branches:
      - "*"
      - "!gh-pages"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt install doxygen

      - name: Generate documentation
        run: |
          mkdir build
          doxygen Doxyfile

      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          target-folder: ${{ github.ref_name }}/documentation
          folder: build/documentation/html/
          clean: true
